import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "CapsCode",
  description: "Generated by CapsCode Company",
  icons: {
    icon: {
      url: "/assets/withoutWards.png",
      type: "image/png",
    },
    shortcut: {
      url: "/assets/withoutWards.png",
      type: "image/png",
    },
  },
  openGraph: {
    title: "CapsCode",
    description: "Generated by CapsCode Company",
    url: "https://capscode.com",
    siteName: "CapsCode",
    locale: "en_US",
    type: "website",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/assets/withoutWards.png" type="image/x-icon" />
        <meta property="og:image" content="/assets/withoutWards.png" />
        <meta name="google-site-verification" content="ymYfjvSdKiU-l4BrhY98KgFhOGRcRpehbUUsIKvpaW8" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              url: "https://caps-code.vercel.app/en",
              logo: "https://caps-code.vercel.app/assets/withoutWards.png", // Full URL to the logo
            }),
          }}
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Clash+Display:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-clash`}
      >
        {children}
      </body>
    </html>
  );
}
